### ISSUE TITLE
BUG-02: Registro de Usuario/Correcion en el campo Contraseña

### ISSUE THREAD

**Issue by Aguila2021** [igrowker/i002-fitfusion-front#156]
**Descripción:** Los demas campos del formulario sus Label coinciden con sus respectivos Placeholder, a diferencia del ultimo campo **Contraseña** cuyo placeholder se visualiza **Repetir Contraseña**

**Precondiciones:** Ingresar al registro de usuario y visializar el formulario

**Pasos de reproducción:**
1- Ingresar a la Home de Fitfusion
2- Presiona el boton **Empieza gratis**
3- Presionar el test Link  **Registrate**
4- Visualizar el formulario

**Resultado Actual**: El ultimo campo se visualiza el label **contraseña** y su placeholder  **Repetir Contraseña**
**Resultado Esperado**: Tanto el label como el placeholder se deveria visualizar **Repetir Contraseña**

Evidencia:
![9oRVmnnTFD](https://github.com/user-attachments/assets/a1d8e43e-abd3-4a7d-b40e-023cccf8cec6)

**Comment by LeandroBustamante025** [comment]
Verificacion:
Fecha:26/07/2024
Veces probados:3
Resultado:PASS
Evidencia:
![verificacin](https://github.com/user-attachments/assets/78b7df2c-478d-4812-ae85-928ff4291ce9)
