### ISSUE TITLE
Detalle de clases

### ISSUE THREAD

**Issue by patrigarcia** [igrowker/i002-fitfusion-front#7]
1. Crear el componente para mostrar los detalles de una clase específica, incluyendo información del profesor y opción para inscripción.
2. 
Crear el componente de calendario, donde el usuario pueda reservar una clase en un día y hora disponible.

**Comment by nmacenco** [comment]
Pendiente Crear el componente de calendario, donde el usuario pueda reservar una clase en un día y hora disponible.
