### ISSUE TITLE
BUG-01-[LOGIN] - Inicio de sesion con un usuario no registrado

### ISSUE THREAD

**Issue by Aguila2021** [igrowker/i002-fitfusion-front#86]
**Descripción:** Cuando se intenta iniciar sesion con un usuario que no fue registrado anteriormente al precionar el boton **Iniciar sesion** me permite la redireccion hacia la pantalla de **Clase**

**Precondiciones:** Ingresar un usuario aleatorio que no haya sido registrado antes

**Datos de prueba**
Correo electronico: leandro@gmail.com
contraseña: 12345678

**Pasos de reproducción:**
1- Ingresar a landing page de FitFusion
2- Presionar el boton **Empieza gratis**
3- Completar los campos **Correo electronico** y **Contraseña**
4- Presionar el boton **Iniciar Sesion**

**Resultado Actual:** Permite loguearse con un Correo electronico y Contraseña no registrados anteriormente

**Resultado Esperado:** Deberia mostrar una validacion que indique que el Correo electronico y Contraseña no estan registrados, y no permita loguearse

**Evidencia:**

![Image](https://github.com/user-attachments/assets/ed19ebee-7bbf-463c-b6ae-9982b9368637)

**Comment by caromorisetti** [comment]
**Templeate:** Verificacion

**Fecha de ejecucion:** 22/07

**Veces probado:** 4

**Estado:** Pass

**Evidencia:**



https://github.com/user-attachments/assets/82fa8f70-4937-45c5-818d-6b82c9fc003b
